services:
  app:
    image: diogowinck/qr-code-reader:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - ./static:/usr/share/nginx/html:ro  # 🚀 Mapeia o static para o Nginx
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
